# Generated by Django 6.0.2 on 2026-03-26 22:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_publico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.CharField(help_text='Ej. Caja Principal, Caja Sala de Ventas', max_length=50)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código Cliente')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombre o Razón Social')),
                ('documento', models.CharField(max_length=20, unique=True, verbose_name='DUI/NIT')),
                ('nrc', models.CharField(blank=True, max_length=20, null=True, verbose_name='NRC')),
                ('giro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Giro')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado (Activo)')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Límite de Crédito')),
                ('plazo_credito', models.PositiveIntegerField(default=0, verbose_name='Plazo Crédito (Días)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=200, verbose_name='Nombre Comercial')),
                ('razon_social', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social')),
                ('nit', models.CharField(max_length=17, unique=True, verbose_name='NIT')),
                ('nrc', models.CharField(blank=True, max_length=10, null=True, verbose_name='NRC (Registro de IVA)')),
                ('tipo_persona', models.CharField(choices=[('natural', 'Persona Natural'), ('juridica', 'Persona Jurídica')], default='natural', max_length=10)),
                ('clasificacion', models.CharField(choices=[('no_contribuyente', 'No Contribuyente'), ('pequeno', 'Pequeño Contribuyente'), ('mediano', 'Mediano Contribuyente'), ('grande', 'Gran Contribuyente')], default='pequeno', max_length=20)),
                ('giro', models.CharField(blank=True, max_length=200, null=True, verbose_name='Giro o Actividad Económica')),
                ('contacto_nombre', models.CharField(blank=True, max_length=150, verbose_name='Persona de Contacto')),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('dias_credito', models.PositiveIntegerField(default=0, help_text='Días de plazo para pagar facturas')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Datos Adicionales')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_publico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_compra', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Compra')),
                ('tipo_comprobante', models.CharField(choices=[('ccf', 'Comprobante de Crédito Fiscal (CCF)'), ('factura', 'Factura de Consumidor Final'), ('recibo', 'Recibo / Otro')], default='ccf', max_length=20)),
                ('numero_comprobante', models.CharField(max_length=50, verbose_name='Número de Documento')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador (No afecta stock)'), ('completada', 'Completada (Stock actualizado)'), ('anulada', 'Anulada (Stock revertido)')], default='borrador', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='core.proveedor')),
            ],
            options={
                'ordering': ['-fecha_compra', '-id'],
                'unique_together': {('proveedor', 'numero_comprobante')},
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código / SKU')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('unidad_medida_base', models.CharField(choices=[('und', 'Unidad (Und)'), ('lb', 'Libra (Lb)'), ('oz', 'Onza (Oz)'), ('kg', 'Kilogramo (Kg)'), ('lt', 'Litro (Lt)'), ('gal', 'Galón (Gal)'), ('mts', 'Metro (Mts)')], default='und', max_length=10, verbose_name='Unidad Base')),
                ('ubicacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ubicación en Bodega')),
                ('stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Stock Actual')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=5.0, max_digits=10, verbose_name='Stock Mínimo')),
                ('stock_maximo', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Stock Máximo')),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Promedio (Unidad Base)')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Venta (Unidad Base)')),
                ('es_vendible', models.BooleanField(default=True, verbose_name='¿Se vende al cliente?')),
                ('es_comprable', models.BooleanField(default=True, verbose_name='¿Se compra a proveedores?')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='core.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Inventario',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PresentacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Botella, Caja x50, Media Libra', max_length=100, verbose_name='Nombre de Presentación')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Barras')),
                ('factor_conversion', models.DecimalField(decimal_places=4, help_text='¿Cuántas unidades base contiene o consume esta presentación?', max_digits=10, verbose_name='Equivalencia en Unidad Base')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Específico')),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='core.producto')),
            ],
            options={
                'verbose_name': 'Presentación',
                'verbose_name_plural': 'Presentaciones',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('tipo', models.CharField(choices=[('entrada_compra', 'Entrada por Compra'), ('ajuste_entrada', 'Ajuste de Entrada (Positivo)'), ('salida_venta', 'Salida por Venta'), ('ajuste_salida', 'Ajuste de Salida (Merma/Daño)')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Movida')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Unitario (Histórico)')),
                ('saldo_cantidad', models.DecimalField(blank=True, decimal_places=2, help_text='Fotografía del stock exacto DESPUÉS de este movimiento', max_digits=10, null=True, verbose_name='Stock Resultante')),
                ('referencia', models.CharField(blank=True, help_text='Ej: Factura #1234, Doc Ajuste #001', max_length=100, null=True, verbose_name='Documento Respaldo')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Justificación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Kardex',
                'verbose_name_plural': 'Kardex de Inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_publico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada (Sobrante / Devolución a favor)'), ('salida', 'Salida (Merma / Daño / Vencimiento)')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad a ajustar', max_digits=10)),
                ('motivo', models.CharField(help_text='Ej: Deterioro del producto', max_length=255)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='core.producto')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SesionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_publico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_esperado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=10)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.caja')),
                ('usuario', models.ForeignKey(help_text='Cajero responsable', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('FCF', 'Factura de Consumidor Final'), ('CCF', 'Comprobante de Crédito Fiscal')], default='FCF', max_length=3)),
                ('codigo_generacion', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('numero_control', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('sello_recepcion', models.CharField(blank=True, max_length=45, null=True)),
                ('condicion_pago', models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='contado', max_length=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('cheque', 'Cheque'), ('otro', 'Otro')], default='efectivo', max_length=20)),
                ('dias_credito', models.PositiveIntegerField(default=0, help_text='Aplica solo si la condición es Crédito')),
                ('numero_factura', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fecha_hora_emision', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('completada', 'Completada'), ('anulada', 'Anulada')], default='borrador', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('sumatoria_gravadas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sumatoria_exentas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sumatoria_no_sujetas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('descuento_global', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('iva_percibido', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('iva_retenido', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_pagar', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
                ('sesion_caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='core.sesioncaja')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('otros', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tipo_afectacion', models.CharField(choices=[('gravada', 'Gravada'), ('exenta', 'Exenta'), ('no_sujeta', 'No Sujeta')], default='gravada', max_length=15)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.venta')),
            ],
        ),
    ]
