# Generated by Django 5.1.4 on 2026-01-18 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código Cliente')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombre o Razón Social')),
                ('documento', models.CharField(max_length=20, unique=True, verbose_name='DUI/NIT')),
                ('nrc', models.CharField(blank=True, max_length=20, null=True, verbose_name='NRC')),
                ('giro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Giro')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado (Activo)')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Límite de Crédito')),
                ('plazo_credito', models.PositiveIntegerField(default=0, verbose_name='Plazo Crédito (Días)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código / SKU')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('tipo', models.CharField(choices=[('materia_prima', '🥩 Producto Padre (Materia Prima)'), ('subproducto', '🍖 Subproducto (Derivado)'), ('producto', '📦 Producto Normal (Compra/Venta)'), ('servicio', '🔧 Servicio (Sin Stock)')], default='producto', max_length=20, verbose_name='Tipo de Producto')),
                ('unidad_medida', models.CharField(choices=[('unidad', 'Unidad (Und)'), ('libra', 'Libra (Lb)'), ('kg', 'Kilogramo (Kg)'), ('metro', 'Metro (Mts)'), ('litro', 'Litro (Lt)')], default='unidad', max_length=20, verbose_name='Unidad')),
                ('ubicacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ubicación en Bodega')),
                ('stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Stock Actual')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=5.0, max_digits=10, verbose_name='Stock Mínimo')),
                ('stock_maximo', models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Stock Máximo')),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Promedio')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de Venta')),
                ('es_vendible', models.BooleanField(default=True, verbose_name='¿Se vende en caja?')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria', verbose_name='Categoría')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subproductos', to='core.producto', verbose_name='Proviene de (Padre)')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Inventario',
                'ordering': ['nombre'],
            },
        ),
    ]
