# Generated by Django 6.0.2 on 2026-02-19 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código Cliente')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombre o Razón Social')),
                ('documento', models.CharField(max_length=20, unique=True, verbose_name='DUI/NIT')),
                ('nrc', models.CharField(blank=True, max_length=20, null=True, verbose_name='NRC')),
                ('giro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Giro')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado (Activo)')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Límite de Crédito')),
                ('plazo_credito', models.PositiveIntegerField(default=0, verbose_name='Plazo Crédito (Días)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=200, verbose_name='Nombre Comercial')),
                ('razon_social', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social')),
                ('nit', models.CharField(max_length=17, unique=True, verbose_name='NIT')),
                ('nrc', models.CharField(blank=True, max_length=10, null=True, verbose_name='NRC (Registro de IVA)')),
                ('tipo_persona', models.CharField(choices=[('natural', 'Persona Natural'), ('juridica', 'Persona Jurídica')], default='natural', max_length=10)),
                ('clasificacion', models.CharField(choices=[('no_contribuyente', 'No Contribuyente'), ('pequeno', 'Pequeño Contribuyente'), ('mediano', 'Mediano Contribuyente'), ('grande', 'Gran Contribuyente')], default='pequeno', max_length=20)),
                ('giro', models.CharField(blank=True, max_length=200, null=True, verbose_name='Giro o Actividad Económica')),
                ('contacto_nombre', models.CharField(blank=True, max_length=150, verbose_name='Persona de Contacto')),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('dias_credito', models.PositiveIntegerField(default=0, help_text='Días de plazo para pagar facturas')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Datos Adicionales')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código / SKU')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('tipo', models.CharField(choices=[('materia_prima', ' Producto Padre (Materia Prima)'), ('subproducto', ' Subproducto (Derivado)'), ('producto', ' Producto Normal (Compra/Venta)'), ('servicio', ' Servicio (Sin Stock)')], default='producto', max_length=20, verbose_name='Tipo de Producto')),
                ('unidad_medida', models.CharField(choices=[('unidad', 'Unidad (Und)'), ('libra', 'Libra (Lb)'), ('kg', 'Kilogramo (Kg)'), ('metro', 'Metro (Mts)'), ('litro', 'Litro (Lt)')], default='unidad', max_length=20, verbose_name='Unidad')),
                ('ubicacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ubicación en Bodega')),
                ('stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Stock Actual')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=5.0, max_digits=10, verbose_name='Stock Mínimo')),
                ('stock_maximo', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Stock Máximo')),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Promedio')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de Venta')),
                ('es_vendible', models.BooleanField(default=True, verbose_name='¿Se vende en caja?')),
                ('es_comprable', models.BooleanField(default=True, verbose_name='¿Se compra a proveedores?')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='core.categoria', verbose_name='Categoría')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subproductos', to='core.producto', verbose_name='Proviene de (Padre)')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Inventario',
                'ordering': ['nombre'],
            },
        ),
    ]
