# Generated by Django 5.1.4 on 2026-01-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_comprable',
            field=models.BooleanField(default=True, verbose_name='¿Se compra a proveedores?'),
        ),
    ]
