# Generated by Django 6.0.2 on 2026-03-30 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso de Dinero (Sencillo, etc.)'), ('egreso', 'Egreso de Dinero (Gasto, Retiro, etc.)')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(help_text='Justificación exacta del movimiento', max_length=255)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('sesion_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='core.sesioncaja')),
                ('usuario', models.ForeignKey(help_text='Usuario que registró el movimiento', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
            },
        ),
    ]
