# Generated by Django 6.0.2 on 2026-02-21 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='updated_at',
            new_name='fecha_actualizacion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='created_at',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='padre',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='unidad_medida',
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida_base',
            field=models.CharField(choices=[('und', 'Unidad (Und)'), ('lb', 'Libra (Lb)'), ('oz', 'Onza (Oz)'), ('kg', 'Kilogramo (Kg)'), ('lt', 'Litro (Lt)'), ('gal', 'Galón (Gal)'), ('mts', 'Metro (Mts)')], default='und', max_length=10, verbose_name='Unidad Base'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='es_vendible',
            field=models.BooleanField(default=True, verbose_name='¿Se vende al cliente?'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Promedio (Unidad Base)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Venta (Unidad Base)'),
        ),
        migrations.CreateModel(
            name='PresentacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Botella, Caja x50, Media Libra', max_length=100, verbose_name='Nombre de Presentación')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Barras')),
                ('factor_conversion', models.DecimalField(decimal_places=4, help_text='¿Cuántas unidades base contiene o consume esta presentación?', max_digits=10, verbose_name='Equivalencia en Unidad Base')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Específico')),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='core.producto')),
            ],
            options={
                'verbose_name': 'Presentación',
                'verbose_name_plural': 'Presentaciones',
            },
        ),
    ]
