# Generated by Django 6.0.2 on 2026-04-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_movimientocaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesioncaja',
            name='fecha_hora_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='saldo_fisico',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lo que el cajero contó físicamente', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sesioncaja',
            name='diferencia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sobrante (positivo) o Faltante (negativo)', max_digits=10, null=True),
        ),
    ]
