# Generated by Django 6.0.2 on 2026-02-22 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_updated_at_producto_fecha_actualizacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('tipo', models.CharField(choices=[('entrada_compra', 'Entrada por Compra'), ('ajuste_entrada', 'Ajuste de Entrada (Positivo)'), ('salida_venta', 'Salida por Venta'), ('ajuste_salida', 'Ajuste de Salida (Merma/Daño)')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Movida')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Unitario (Histórico)')),
                ('saldo_cantidad', models.DecimalField(decimal_places=2, help_text='Fotografía del stock exacto DESPUÉS de este movimiento', max_digits=10, verbose_name='Stock Resultante')),
                ('referencia', models.CharField(blank=True, help_text='Ej: Factura #1234, Doc Ajuste #001', max_length=100, null=True, verbose_name='Documento Respaldo')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Justificación')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Movimiento de Kardex',
                'verbose_name_plural': 'Kardex de Inventario',
                'ordering': ['-fecha'],
            },
        ),
    ]
