# Generated by Django 5.1.4 on 2026-02-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_es_comprable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock_maximo',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Stock Máximo'),
        ),
    ]
