# Generated by Django 5.1.4 on 2026-02-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_producto_stock_maximo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Stock Máximo'),
        ),
    ]
