# Generated by Django 6.0.2 on 2026-02-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_movimientoinventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='saldo_cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fotografía del stock exacto DESPUÉS de este movimiento', max_digits=10, null=True, verbose_name='Stock Resultante'),
        ),
    ]
