# Generated by Django 6.0.2 on 2026-04-02 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sesioncaja_fecha_hora_cierre_sesioncaja_saldo_fisico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesioncaja',
            name='fecha_cierre',
        ),
        migrations.RemoveField(
            model_name='sesioncaja',
            name='saldo_real',
        ),
    ]
