# Generated by Django 6.0.2 on 2026-04-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_sesioncaja_fecha_cierre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesioncaja',
            name='caja',
        ),
        migrations.RemoveField(
            model_name='movimientocaja',
            name='sesion_caja',
        ),
        migrations.RemoveField(
            model_name='movimientocaja',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='sesioncaja',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='sesion_caja',
        ),
        migrations.AddField(
            model_name='venta',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('pagado', 'Pagado')], default='pendiente', max_length=15),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('sellada', 'Sellada'), ('anulada', 'Anulada')], default='borrador', max_length=20),
        ),
        migrations.DeleteModel(
            name='Caja',
        ),
        migrations.DeleteModel(
            name='MovimientoCaja',
        ),
        migrations.DeleteModel(
            name='SesionCaja',
        ),
    ]
