# Generated by Django 5.1.4 on 2026-02-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_producto_stock_maximo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=200, verbose_name='Nombre Comercial')),
                ('razon_social', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social')),
                ('nit', models.CharField(max_length=17, unique=True, verbose_name='NIT')),
                ('nrc', models.CharField(blank=True, max_length=10, null=True, verbose_name='NRC (Registro de IVA)')),
                ('tipo_persona', models.CharField(choices=[('natural', 'Persona Natural'), ('juridica', 'Persona Jurídica')], default='natural', max_length=10)),
                ('clasificacion', models.CharField(choices=[('no_contribuyente', 'No Contribuyente'), ('pequeno', 'Pequeño Contribuyente'), ('mediano', 'Mediano Contribuyente'), ('grande', 'Gran Contribuyente')], default='pequeno', max_length=20)),
                ('giro', models.CharField(blank=True, max_length=200, null=True, verbose_name='Giro o Actividad Económica')),
                ('contacto_nombre', models.CharField(blank=True, max_length=150, verbose_name='Persona de Contacto')),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('dias_credito', models.PositiveIntegerField(default=0, help_text='Días de plazo para pagar facturas')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Datos Adicionales')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('materia_prima', ' Producto Padre (Materia Prima)'), ('subproducto', ' Subproducto (Derivado)'), ('producto', ' Producto Normal (Compra/Venta)'), ('servicio', ' Servicio (Sin Stock)')], default='producto', max_length=20, verbose_name='Tipo de Producto'),
        ),
    ]
