# Generated by Django 6.0.2 on 2026-03-13 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_compra_detallecompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('FCF', 'Factura de Consumidor Final'), ('CCF', 'Comprobante de Crédito Fiscal')], default='FCF', max_length=3)),
                ('condicion_pago', models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='contado', max_length=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('cheque', 'Cheque'), ('otro', 'Otro')], default='efectivo', max_length=20)),
                ('dias_credito', models.PositiveIntegerField(default=0, help_text='Aplica solo si la condición es Crédito')),
                ('numero_factura', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('completada', 'Completada'), ('anulada', 'Anulada')], default='borrador', max_length=20)),
                ('sumatoria_gravadas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sumatoria_exentas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sumatoria_no_sujetas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('descuento_global', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('iva_percibido', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('iva_retenido', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_pagar', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
            ],
        ),
    ]
