# Generated by Django 6.0.2 on 2026-04-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_solicitudacceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador (Digitando factura)'), ('en_transito', 'En Tránsito (Pagada, esperando llegada)'), ('recibida', 'Recibida en Bodega (Stock actualizado)'), ('anulada', 'Anulada (Stock revertido)')], default='borrador', max_length=20),
        ),
    ]
