# Generated by Django 6.0.2 on 2026-04-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_compra_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='cantidad_recibida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
