# Generated by Django 6.0.2 on 2026-03-13 23:48

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_detalleventa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='fecha_emision',
        ),
        migrations.AddField(
            model_name='venta',
            name='codigo_generacion',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_hora_emision',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='numero_control',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='sello_recepcion',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
