# Generated by Django 6.0.2 on 2026-04-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_detallecompra_cantidad_recibida'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Notas de Resolución (Diferencias)'),
        ),
    ]
