# Generated by Django 6.0.2 on 2026-03-24 02:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_venta_fecha_emision_venta_codigo_generacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='id_publico',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='compra',
            unique_together={('proveedor', 'numero_comprobante')},
        ),
    ]
