# Generated by Django 6.0.2 on 2026-03-26 03:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_compra_id_publico_alter_compra_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_publico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada (Sobrante / Devolución a favor)'), ('salida', 'Salida (Merma / Daño / Vencimiento)')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad a ajustar', max_digits=10)),
                ('motivo', models.CharField(help_text='Ej: Queso arruinado en bodega, Error de conteo inicial', max_length=255)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='core.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
