# Generated by Django 6.0.2 on 2026-04-26 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_compra_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='presentacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.presentacionproducto'),
        ),
    ]
