# Generated by Django 6.0.2 on 2026-05-10 20:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_detalleventa_presentacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='condicion_pago',
            field=models.CharField(choices=[('contado', 'Contado (Pago Inmediato)'), ('credito', 'Crédito (Cuentas por Pagar)')], default='contado', max_length=10),
        ),
        migrations.AddField(
            model_name='compra',
            name='dias_credito',
            field=models.PositiveIntegerField(default=0, help_text='Días de plazo si es de crédito'),
        ),
        migrations.AddField(
            model_name='compra',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('parcial', 'Abono Parcial Registrado'), ('pagado', 'Pagado en su Totalidad'), ('anulado', 'Cobro Anulado')], default='pendiente', max_length=15),
        ),
        migrations.CreateModel(
            name='PagoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo (Caja Chica)'), ('transferencia', 'Transferencia Bancaria'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta Corporativa')], max_length=20)),
                ('comprobante_pago', models.CharField(blank=True, help_text='Número de cheque o referencia de transferencia', max_length=100, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.compra')),
                ('usuario', models.ForeignKey(help_text='Usuario que registró la salida de dinero', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
