# Generated by Django 6.0.2 on 2026-05-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20260525_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha_hora_emision']},
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='dias_credito',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
