# Generated by Django 6.0.2 on 2026-05-29 23:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_venta_options_venta_fecha_vencimiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_generacion', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('monto_revertido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo_anulacion', models.TextField(help_text='Razón por la cual se anuló la factura y se emitió la NC.')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('emitida_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('venta_origen', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='nota_credito', to='core.venta')),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
